services:
  - docker

before_script:
 - bash scripts/write_envs_to_file.sh
 - docker-compose -f docker-compose.dev.yml -f docker-compose.prod.yml up -d --build
 - ./scripts/wait_for_backend.sh
 - ./deploy.sh

script:
 - docker exec backend python3 manage.py migrate
 - wget http://localhost:8000
 - docker exec backend python3 manage.py test

after_script:
 - docker-compose down
