version: '3.7'

services:

  backend:
    volumes:
      - backend-logs:/backend/run/log
#    ports:
#      Port definitions from the .dev file will be carried on to prod
#      so even if there is no port defined here, the docker image will be exposed
#      as configured in the .dev file
    networks:
      - network
    env_file:
      - backend.prod.env
      - database.prod.env
    environment:
     - CI
     - TRAVIS
     - TRAVIS_PULL_REQUEST_SLUG
     - DJANGO_SETTINGS_MODULE=match4healthcare.settings.production
     - PRODUCTION=True
    command: gunicorn -c /backend/gunicorn.conf.py match4healthcare.wsgi
    depends_on:
      - database


  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
     - db-data:/var/lib/postgresql/data
     - db-backup:/backups/
    restart: always
    env_file:
     - database.prod.env
    expose:
     -  5432
    networks:
     - network
    command: postgres -c config_file=/etc/postgresql.conf

networks:
 network:

volumes:
  backend-logs:
  db-data:
  db-backup:
