version: '3.7'

services:

  backend:
    volumes:
      - './backend:/match4healthcare-backend'
#    ports:
#      Port definitions from the .dev file will be carried on to prod
#      so even if there is no port defined here, the docker image will be exposed
#      as configured in the .dev file
    networks:
      - network
    env_file:
      - backend.prod.env
      - database.prod.env
    environment:
     - DJANGO_SETTINGS_MODULE=match4healthcare.settings.production
     - PRODUCTION=True
    user: ${BACKEND_USER:-0}
    command: gunicorn -c /match4healthcare-backend/gunicorn.conf.py match4healthcare.wsgi
    depends_on:
      - database


  database:
    image: postgres:12
    volumes:
     - ./database/data:/var/lib/postgresql/data
     - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
     - ./database/postgresql.conf:/etc/postgresql.conf
     - ./database/backups:/backups/
    restart: always
    env_file:
     - database.prod.env
    expose:
     -  5432
    networks:
     - network
    command: postgres -c config_file=/etc/postgresql.conf

networks:
 network:

volumes:
  backend-run:
