version: '3.7'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/match4healthcare-backend'
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=match4everyone.settings.development
      - CI
      - TRAVIS
      - TRAVIS_PULL_REQUEST_SLUG
      - PYTHONPATH=/backend # needed for django-admin to find the module
    user: ${BACKEND_USER:-0}
